version: '3.8' 

services:
  mysql:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: appdata
      MYSQL_USER: user123     
      MYSQL_PASSWORD: password123 
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  
    ports:
      - "3366:3306"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_USER=user123
      - DB_PASSWORD=password123
      - DB_NAME=appdata
    ports:
      - "3005:3000"
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"  
    environment:
      - NODE_ENV=development  # Utiliser le mode développement
    volumes:
      - ./frontend:/app

volumes:
  db_data:
